server:
 port: 8882

spring:
 application:
  name: pos-products

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8880/eureka
 instance:
  instance-id: pos-products-8881
  prefer-ip-address: true