server:
 port: 8881  #端口号

spring:
 application:
  name: pos-gateway
 cloud:
  gateway: #网关路由配置
   discovery:
    locator:
     enabled: true #默认值为 true，即默认开启从注册中心动态创建路由的功能，利用微服务名进行路由
   routes:
    - id: pos_products_server   #商品
      uri: http://localhost:8882          #匹配后提供服务的路由地址
      predicates:
       - Path=/api/products/**               #断言，路径匹配 注意：Path 中 P 为大写
       - Method=GET #只能时 GET 请求时，才能访问

    - id: pos_carts_server   #购物车
      uri: http://localhost:8883          #匹配后提供服务的路由地址
      predicates:
        - Path=/api/carts/**              #断言，路径匹配 注意：Path 中 P 为大写

    - id: pos_orders_server   #订单
      uri: http://localhost:8884          #匹配后提供服务的路由地址
      predicates:
        - Path=/api/orders/**              #断言，路径匹配 注意：Path 中 P 为大写

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka
  instance:
    hostname: cloud-gateway-service

