openapi: "3.0.0"
info:
  version: 1.0.0
  title: Delivery
  license:
    name: MIT
paths:
  /deliveries:
    get:
      summary: List all deliveries
      operationId: listDeliveries
      tags:
        - delivery
      responses:
        '200':
          description: A paged array of deliveries
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Deliveries"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /deliveries/{orderId}:
    get:
      summary: Info for a specific delivery
      operationId: showDeliveryByOrderId
      tags:
        - order
      parameters:
        - name: orderId
          in: path
          required: true
          description: The id of the order
          schema:
            type: integer
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Delivery"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /deliveries/confirm/{orderId}:
    get:
      summary: confirm a order
      operationId: confirmOrder
      tags:
        - order
      parameters:
        - name: orderId
          in: path
          required: true
          description: The id of the order
          schema:
            type: integer
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Delivery"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:
    Deliveries:
      type: array
      items:
        $ref: "#/components/schemas/Delivery"
    Delivery:
      type: object
      properties:
        id:
          type: integer
          format: int32
        company:
          type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string